export const IB_APTITUDE = [
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/problems-on-trains/", name: "Problems on Trains" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/time-and-distance/", name: "Time and Distance" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/height-and-distance/", name: "Height and Distance" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/time-and-work/", name: "Time and Work" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/simple-interest/", name: "Simple Interest" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/compound-interest/", name: "Compound Interest" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/profit-and-loss/", name: "Profit and Loss" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/partnership/", name: "Partnership" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/percentage/", name: "Percentage" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/problems-on-ages/", name: "Problems on Ages" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/calendar/", name: "Calendar" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/clock/", name: "Clock" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/average/", name: "Average" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/area/", name: "Area" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/volume-and-surface-area/", name: "Volume and Surface Area" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/permutation-and-combination/", name: "Permutation and Combination" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/numbers/", name: "Numbers" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/problems-on-numbers/", name: "Problems on Numbers" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/problems-on-hcf-and-lcm/", name: "Problems on H.C.F and L.C.M" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/decimal-fraction/", name: "Decimal Fraction" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/simplification/", name: "Simplification" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/square-root-and-cube-root/", name: "Square Root and Cube Root" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/surds-and-indices/", name: "Surds and Indices" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/ratio-and-proportion/", name: "Ratio and Proportion" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/chain-rule/", name: "Chain Rule" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/pipes-and-cistern/", name: "Pipes and Cistern" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/boats-and-streams/", name: "Boats and Streams" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/alligation-or-mixture/", name: "Alligation or Mixture" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/logarithm/", name: "Logarithm" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/races-and-games/", name: "Races and Games" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/stocks-and-shares/", name: "Stocks and Shares" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/probability/", name: "Probability" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/true-discount/", name: "True Discount" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/bankers-discount/", name: "Banker's Discount" },
  { tag:"Arithmetic Aptitude", url: "https://www.indiabix.com/aptitude/odd-man-out-and-series/", name: "Odd Man Out and Series" },

  { tag:"Data Interpretation", url:"https://www.indiabix.com/data-interpretation/table-charts/", name:" Table Charts"},
  { tag:"Data Interpretation", url:"https:/ / www.indiabix.com / data - interpretation / bar - charts / ", name:"Bar Charts"},
  { tag:"Data Interpretation", url:"https://www.indiabix.com/data-interpretation/pie-charts/", name:"Pie Charts"},
  { tag:"Data Interpretation", url:"https://www.indiabix.com/data-interpretation/line-charts/", name:"Line Charts"},

  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/random", name:"Aptitude Test (Random Questions)"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/1", name:"Aptitude Test 1"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/2", name:"Aptitude Test 2"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/3", name:"Aptitude Test 3"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/4", name:"Aptitude Test 4"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/5", name:"Aptitude Test 5"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/6", name:"Aptitude Test 6"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/7", name:"Aptitude Test 7"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/8", name:"Aptitude Test 8"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/9", name:"Aptitude Test 9"},
  { tag:"Online Aptitude Test", url:"https://www.indiabix.com/online-test/aptitude-test/10", name:"Aptitude Test 10"},

  { tag:"Data Interpretation Test", url:"https://www.indiabix.com/online-test/data-interpretation-test/71", name:"Data Interpretation Test 1"},
  { tag:"Data Interpretation Test", url:"https://www.indiabix.com/online-test/data-interpretation-test/72", name:"Data Interpretation Test 2"},
  { tag:"Data Interpretation Test", url:"https://www.indiabix.com/online-test/data-interpretation-test/74", name:"Data Interpretation Test 4"},
  { tag:"Data Interpretation Test", url:"https://www.indiabix.com/online-test/data-interpretation-test/73", name:"Data Interpretation Test 3"},
  { tag:"Data Interpretation Test", url:"https://www.indiabix.com/online-test/data-interpretation-test/75", name:"Data Interpretation Test 5"},

  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/spotting-errors/", name: "Spotting Errors" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/synonyms/", name: "Synonyms" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/antonyms/", name: "Antonyms" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/selecting-words/", name: "Selecting Words" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/spellings/", name: "Spellings" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/sentence-formation/", name: "Sentence Formation" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/ordering-of-words/", name: "Ordering of Words" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/sentence-correction/", name: "Sentence Correction" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/sentence-improvement/", name: "Sentence Improvement" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/completing-statements/", name: "Completing Statements" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/ordering-of-sentences/", name: "Ordering of Sentences" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/paragraph-formation/", name: "Paragraph Formation" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/closet-test/", name: "Closet Test" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/comprehension/", name: "Comprehension" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/one-word-substitutes/", name: "One Word Substitutes" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/idioms-and-phrases/", name: "Idioms and Phrases" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/change-of-voice/", name: "Change of Voice" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/change-of-speech/", name: "Change of Speech" },
  { tag:"Verbal Ability", url: "https://www.indiabix.com/verbal-ability/verbal-analogies/", name: "Verbal Analogies" },

  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/number-series/', name: 'Number Series' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/letter-and-symbol-series/', name: 'Letter and Symbol Series' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/verbal-classification/', name: 'Verbal Classification' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/essential-part/', name: 'Essential Part' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/analogies/', name: 'Analogies' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/artificial-language/', name: 'Artificial Language' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/matching-definitions/', name: 'Matching Definitions' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/making-judgments/', name: 'Making Judgments' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/verbal-reasoning/', name: 'Verbal Reasoning' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/logical-problems/', name: 'Logical Problems' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/logical-games/', name: 'Logical Games' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/analyzing-arguments/', name: 'Analyzing Arguments' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/statement-and-assumption/', name: 'Statement and Assumption' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/course-of-action/', name: 'Course of Action' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/statement-and-conclusion/', name: 'Statement and Conclusion' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/theme-detection/', name: 'Theme Detection' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/cause-and-effect/', name: 'Cause and Effect' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/statement-and-argument/', name: 'Statement and Argument' },
  { tag:"Logical Reasoning", url: 'https://www.indiabix.com/logical-reasoning/logical-deduction/', name: 'Logical Deduction' },

  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/logical-sequence-of-words/", name: "Logical Sequence of Words" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/blood-relation-test/", name: "Blood Relation Test" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/syllogism/", name: "Syllogism" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/series-completion/", name: "Series Completion" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/cause-and-effect/", name: "Cause and Effect" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/dice/", name: "Dice" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/venn-diagrams/", name: "Venn Diagrams" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/cube-and-cuboid/", name: "Cube and Cuboid" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/analogy/", name: "Analogy" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/seating-arrangement/", name: "Seating Arrangement" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/character-puzzles/", name: "Character Puzzles" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/direction-sense-test/", name: "Direction Sense Test" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/classification/", name: "Classification" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/data-sufficiency/", name: "Data Sufficiency" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/arithmetic-reasoning/", name: "Arithmetic Reasoning" },
  { tag:"Verbal Reasoning", url: "https://www.indiabix.com/verbal-reasoning/verification-of-truth/", name: "Verification of Truth" }


];
